### ISSUE TITLE
Adding mod mesh after creating BCs results in duplicate BCs 

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#286]
Really easy to repro - see attached GIF. The duplicate BCs are actually created and results in a solver error if the job is submitted.

![Peek 2020-09-08 19-45](https://user-images.githubusercontent.com/23110600/92544797-f956d180-f20b-11ea-954c-2a3e87384395.gif)

**Comment by bradymadams** [comment]
I'm going to re-open this because we have a very similar problem when these same steps are performed after a validation.

**Comment by dougkenik** [comment]
There is also a crash if you follow these steps:

Steps:
1.	Add some anchors / forces to an object
2.	Switch back to normal view
3.	Save project file
4.	Load project file
5.	Copy object from project file (duplicate)
Expected:
1.	Object gets duplicated
Actual: 
1.	 Message pops up about placing object. No progress is shown, nothing happens.
2.	Logs: 2020-09-15 11:42:33,965 - ERROR - [Thread-2] UM.Logger.logException [106]: Exception: Job <cura.MultiplyObjectsJob.MultiplyObjectsJob object at 0xb96f608> caused an exception 
2020-09-15 11:42:33,975 - ERROR - [Thread-2] UM.Logger.logException [110]: Traceback (most recent call last):
2020-09-15 11:42:33,989 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/4.7/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 132, in run
2020-09-15 11:42:34,000 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/4.7/build/inst/lib/python3.5/site-packages/cura/MultiplyObjectsJob.py", line 73, in run
2020-09-15 11:42:34,006 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/env/4.7/inst/lib/python3.5/copy.py", line 166, in deepcopy
2020-09-15 11:42:34,017 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/4.7/build/inst/lib/python3.5/site-packages/cura/Scene/CuraSceneNode.py", line 151, in __deepcopy__
2020-09-15 11:42:34,042 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/env/4.7/inst/lib/python3.5/copy.py", line 166, in deepcopy
2020-09-15 11:42:34,055 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/4.7/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 111, in __deepcopy__
2020-09-15 11:42:34,071 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/env/4.7/inst/lib/python3.5/copy.py", line 166, in deepcopy
2020-09-15 11:42:34,091 - ERROR - [Thread-2] UM.Logger.logException [110]:   File "/build/4.7/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 101, in __deepcopy__
2020-09-15 11:42:34,104 - ERROR - [Thread-2] UM.Logger.logException [110]: TypeError: __init__() missing 1 required positional argument: 'name'
