### ISSUE TITLE
numpy-stl module missing

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#31]
Build 38: https://build.fea.cloud/job/2019.1/job/smartslice-cura-plugin/38/

SmartSlice plugin fails to import pywim because numpy-stl is missing. Also, should teton-pywim version be 19.1.39?

```
2019-11-15 07:35:11,662 - INFO - [MainThread] SmartSliceExtension.utils.SystemUtils.registerThirdPartyModules [48]: Adding module: teton-pywim-19.1.33.32
2019-11-15 07:35:11,662 - INFO - [MainThread] SmartSliceExtension.utils.SystemUtils.registerThirdPartyModules [48]: Adding module: teton-3mf-19.1.7
2019-11-15 07:35:11,665 - ERROR - [MainThread] UM.Logger.logException [84]: Exception: Import error loading module SmartSliceExtension
2019-11-15 07:35:11,667 - ERROR - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2019-11-15 07:35:11,669 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/PluginRegistry.py", line 540, in _findPlugin
2019-11-15 07:35:11,670 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/4.4/inst/lib/python3.5/imp.py", line 245, in load_module
2019-11-15 07:35:11,672 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/4.4/inst/lib/python3.5/imp.py", line 217, in load_package
2019-11-15 07:35:11,674 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 693, in _load
2019-11-15 07:35:11,675 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2019-11-15 07:35:11,677 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2019-11-15 07:35:11,679 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-11-15 07:35:11,681 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/__init__.py", line 18, in <module>
2019-11-15 07:35:11,682 - ERROR - [MainThread] UM.Logger.logException [88]:     import pywim
2019-11-15 07:35:11,684 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/3rd-party/cpython-common/teton-pywim-19.1.33.32/pywim/__init__.py", line 304, in <module>
2019-11-15 07:35:11,686 - ERROR - [MainThread] UM.Logger.logException [88]:     from . import abaqus, am, chop, fea, http, micro, optimization, smartslice
2019-11-15 07:35:11,688 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/3rd-party/cpython-common/teton-pywim-19.1.33.32/pywim/chop/__init__.py", line 2, in <module>
2019-11-15 07:35:11,689 - ERROR - [MainThread] UM.Logger.logException [88]:     from . import machine, mesh, model, slicer
2019-11-15 07:35:11,691 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/3rd-party/cpython-common/teton-pywim-19.1.33.32/pywim/chop/mesh.py", line 1, in <module>
2019-11-15 07:35:11,693 - ERROR - [MainThread] UM.Logger.logException [88]:     import threemf
2019-11-15 07:35:11,694 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/3rd-party/cpython-common/teton-3mf-19.1.7/threemf/__init__.py", line 96, in <module>
2019-11-15 07:35:11,696 - ERROR - [MainThread] UM.Logger.logException [88]:     from . import extension, geom, mesh, model, io
2019-11-15 07:35:11,698 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/brady/.local/share/cura/4.4/plugins/SmartSlicePlugin/SmartSliceExtension/3rd-party/cpython-common/teton-3mf-19.1.7/threemf/geom.py", line 6, in <module>
2019-11-15 07:35:11,700 - ERROR - [MainThread] UM.Logger.logException [88]:     import stl
```

**Comment by bradymadams** [comment]
This was an issue with the AppImage build from Ultimaker. See: https://github.com/Ultimaker/cura-build-environment/issues/74
