### ISSUE TITLE
Adding 0 to beginning of skin angles list crashes in Smart Slice plugin

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#365]
See GIF. I encountered this when I wanted to add a 0 angle to the beginning of the list.

![skin_angles_crash](https://user-images.githubusercontent.com/23110600/102097080-b1cf7b00-3de2-11eb-876c-35b4cd16a3a1.gif)

```
Traceback (most recent call last):
  File "/build/4.6/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 1013, in event
  File "/build/4.6/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 464, in event
  File "/build/4.6/build/inst/lib/python3.5/site-packages/UM/Event.py", line 218, in call
  File "/build/4.6/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 332, in __performEmit
  File "/home/brady/.local/share/cura/4.6/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 240, in _onExtruderPropertyChanged
    list(filter(lambda p: p.name == key, self._extruder_properties))
  File "/home/brady/.local/share/cura/4.6/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 361, in confirmPendingChanges
    self.connector.updateStatus()
  File "/home/brady/.local/share/cura/4.6/plugins/SmartSlicePlugin/SmartSliceCloudConnector.py", line 1006, in updateStatus
    job, self._proxy.errors = self.smartSliceJobHandle.checkJob(show_extruder_warnings=show_warnings)
  File "/home/brady/.local/share/cura/4.6/plugins/SmartSlicePlugin/SmartSliceJobHandler.py", line 171, in checkJob
    if len(skin_angles) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by AijunHall** [comment]
Deleting a bracket from either side of the angle list also produces the same crash

![recording](https://user-images.githubusercontent.com/54338983/104663001-e1430300-5680-11eb-9a97-240cc7ef4c5b.gif)

```
Traceback (most recent call last):
  File "C:\dev\Cura\cura\CuraApplication.py", line 1063, in event
  File "C:\Users\AijunHall\source\repos\UM\UM\Qt\QtApplication.py", line 464, in event
  File "C:\Users\AijunHall\source\repos\UM\UM\Event.py", line 218, in call
  File "C:\Users\AijunHall\source\repos\UM\UM\Signal.py", line 332, in __performEmit
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSlicePropertyHandler.py", line 240, in _onExtruderPropertyChanged
    list(filter(lambda p: p.name == key, self._extruder_properties))
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSlicePropertyHandler.py", line 361, in confirmPendingChanges
    self.connector.updateStatus()
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSliceCloudConnector.py", line 1016, in updateStatus
    job, self._proxy.errors = self.smartSliceJobHandle.checkJob(show_extruder_warnings=show_warnings)
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSliceJobHandler.py", line 171, in checkJob
    if len(skin_angles) > 0:
TypeError: object of type 'NoneType' has no len()

```
