### ISSUE TITLE
No Optimize Results Load Crash

### ISSUE THREAD

**Issue by jake-kirkland-teton** [tetonsim/is-cura-ui#368]
If you run an optimize and get a result that cannot be optimized, and then save that project, Cura will crash when you load the project.

**Comment by bradymadams** [comment]
Any reason to believe this is or isn't related to #375?

**Comment by AijunHall** [comment]
Heres the Traceback I get when stubbing this crash out:

```
Traceback (most recent call last):
  File "C:\dev\Cura\cura\CuraApplication.py", line 1063, in event
  File "C:\Users\AijunHall\source\repos\UM\UM\Qt\QtApplication.py", line 464, in event
  File "C:\Users\AijunHall\source\repos\UM\UM\Event.py", line 218, in call
  File "C:\Users\AijunHall\source\repos\UM\UM\Signal.py", line 332, in __performEmit
  File "C:\dev\Cura\plugins\SmartSlicePlugin\stage\SmartSliceScene.py", line 516, in _process_mesh_analysis
    job.callback()
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSliceExtension.py", line 270, in afterSmartSliceNodeInit
    self.cloud.processAnalysisResult(selected_row)
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSliceCloudConnector.py", line 1005, in processAnalysisResult
    resultData = ResultTableData.analysisToResultDict(0, job.getResult().analyses[0])
  File "C:\dev\pywim_r20.2\pywim\__init__.py", line 99, in __getitem__
    return super().__getitem__(key)
IndexError: list index out of range

```

**Comment by AijunHall** [comment]
> Any reason to believe this is or isn't related to 375?

@bradymadams I've got the file in question from 375, and although the tracebacks aren't exactly the same, they both have the same issue of an unexpected NoneType in the same file, so they are somewhat related
