### ISSUE TITLE
Load wheel doesn't disappear when clicking off the part

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#519]
Steps to reproduce:

1. Define a load.
2. Click off the part. The load visualization remains.

Expected: load visualization disappears when you click off the part.

Tested using SmartSlicePlugin-r21.0.22

[UMS5_lever.zip](https://github.com/tetonsim/is-cura-ui/files/6400997/UMS5_lever.zip)

![image](https://user-images.githubusercontent.com/34459028/116604126-fa4b8900-a8ea-11eb-95d1-6ae316d83e20.png)

**Comment by dougkenik** [comment]
Traceback when this happens below. Looks like our tool thinks we are selecting a face:

2021-04-29 15:06:12,462 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]: Exception: Unable to select face
2021-04-29 15:06:12,476 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]: Traceback (most recent call last):
2021-04-29 15:06:12,480 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:   File "C:\Users\DougKenik\dev\cura\Cura\plugins\SmartSlicePlugin\select_tool\SmartSliceSelectTool.py", line 151, in _onSelectedFaceChanged
2021-04-29 15:06:12,484 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:     self._getSelectedTriangles(current_surface, bc_node)
2021-04-29 15:06:12,487 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:   File "C:\Users\DougKenik\dev\cura\Cura\plugins\SmartSlicePlugin\select_tool\SmartSliceSelectTool.py", line 206, in _getSelectedTriangles
2021-04-29 15:06:12,491 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:     selected_face = interactive_mesh.select_concave_face(face_id)
2021-04-29 15:06:12,495 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:   File "C:\Users\DougKenik\dev\teton\pywim\pywim\geom\tri.py", line 574, in select_concave_face
2021-04-29 15:06:12,498 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]:     tri = next(t for t in self.triangles if t.id == tri)
2021-04-29 15:06:12,502 - ERROR - [MainThread] SmartSlicePlugin.select_tool.SmartSliceSelectTool._onSelectedFaceChanged [153]: StopIteration

**Comment by dougkenik** [comment]
So - for some reason the body becomes un-highlighted in blue after we select the face. When you click off the model, but the arrow remains, and SS thinks it needs to select a face. If you rotate the model at all, and then select off the body, everything hides like it should.
