### ISSUE TITLE
Removing Model from Build Plate Crashes Cura

### ISSUE THREAD

**Issue by CodyFagley** [tetonsim/is-cura-ui#87]
Loading a model and deleting it throws the following set of CRITICAL error messages in Selection Handle (log attached)
```
2020-02-18 11:27:49,370 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [61]: An uncaught error has occurred!
2020-02-18 11:27:49,374 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: Traceback (most recent call last):
2020-02-18 11:27:49,377 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CuraActions.py", line 109, in deleteSelection
2020-02-18 11:27:49,380 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Operations/Operation.py", line 50, in push
2020-02-18 11:27:49,383 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Operations/OperationStack.py", line 54, in push
2020-02-18 11:27:49,386 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Operations/GroupedOperation.py", line 48, in redo
2020-02-18 11:27:49,388 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Operations/RemoveSceneNodeOperation.py", line 40, in redo
2020-02-18 11:27:49,390 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Scene/Selection.py", line 33, in remove
2020-02-18 11:27:49,392 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Scene/Selection.py", line 191, in _onTransformationChanged
2020-02-18 11:27:49,394 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 212, in emit
2020-02-18 11:27:49,396 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 315, in __performEmit
2020-02-18 11:27:49,398 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "/home/cfagley/.local/share/cura/4.4/plugins/is-cura-ui/SmartSlicePlugin/select_tool/SmartSliceSelectHandle.py", line 54, in _onSelectionCenterChanged
2020-02-18 11:27:49,400 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:     self.setTransformation(obj.getLocalTransformation())
2020-02-18 11:27:49,402 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: AttributeError: 'NoneType' object has no attribute 'getLocalTransformation'
```
[stderr.log](https://github.com/tetonsim/is-cura-ui/files/4220987/stderr.log)

**Comment by CodyFagley** [comment]
Resolved with most recent push in 'cf-r20-UI-Validation'
